---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - SITE=test-with-ssl.yml ANSIBLE_VERSION=latest
  - SITE=test-without-ssl.yml ANSIBLE_VERSION=latest
#  - SITE=test.yml ANSIBLE_VERSION=2.1.0.0

branches:
  only:
    - master

addons:
  mariadb: '10.1'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl nginx php5 php5-cli php5-fpm php5-curl php5-imap php5-xmlrpc php5-mysqlnd
  - curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install --no-binary ansible ansible; else pip install --no-binary ansible ansible==$ANSIBLE_VERSION; fi

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install ansible-lint
  - pip install ansible-lint

  - sudo ./tests/generate-ssl.sh

before_script:
  - mysql -u root -e "CREATE DATABASE roundcube;"
  - mysql -u root -e "GRANT SELECT,INSERT,UPDATE,DELETE ON roundcube.* TO 'roundcube'@'127.0.0.1' IDENTIFIED BY 'tr4v1s';"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # ansible-lint checks for best practice
  - ansible-lint tests/$SITE

  # simple checks (@todo add proper tests)
  - test -e /opt/roundcube/logs
  - test -e /opt/roundcube/roundcubemail-1.2.0
  - test -e /opt/roundcube/roundcubemail-1.2.0/config/config.inc.php
  - test -e /opt/roundcube/sessions
  - test -e /opt/roundcube/tmp
  - test -e /opt/roundcube/usr
  - curl https://localhost
  - curl http://localhost

after_failure:
  - ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
  - sudo service nginx status
  - ansible --version
  - curl http://127.0.0.1/
  - curl http://localhost/
  - nginx -v
  - ls -lh /opt/roundcube/
  - ls -lh /opt/roundcube/round*
  - cat /opt/roundcube/round*/config/config.inc.php
  - composer -v
  - curl https://localhost:444
  - curl http://localhost:444

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/